const String sateliteBackSide =
    'For researchers, optimizing time spent in the field is paramount. Before embarking on meticulously planned campaigns, extensive data processing and model building are already underway. It is imperative that none of this valuable data is missed during fieldwork. To address this challenge, we are actively developing solutions to grant researchers real-time access to datasets. This approach ensures that researchers can maximize their time in the field, enabling them to gather as much data as possible and make informed decisions on the fly.';

const String teamBackSide =
    'In collaborative fieldwork, teamwork is indispensable. To facilitate seamless collaboration, we offer a comprehensive solution ensuring that data is accessible to all team members at any time. Whether referencing data from previous campaigns or avoiding redundant measurements of the same location, our platform empowers teams to stay agile and respond directly to campaign outcomes. Embracing a project-based approach, our system enables team members to gather datasets collectively, exchange information, and collaborate effortlessly anytime, anywhere. This flexibility ensures efficient data collection and analysis while fostering real-time collaboration among team members';

const String dataVisulizationBackSide = '''
In the dynamic environment of fieldwork, time is precious. TerraTrace recognizes the importance of swift data interpretation after long days in the field. That's why we provide all the necessary data interpretation tools directly in the field. Our platform enables live visualization of data on-screen, empowering users to select different datasets in real-time from our data distribution network. This capability allows for immediate analysis, enabling researchers to draw preliminary conclusions and make informed decisions about where to focus their attention or explore new areas. Whether it's basic statistics or advanced data modeling, TerraTrace ensures that your cognitive resources remain free to concentrate on gathering data, streamlining your fieldwork process.
''';

const String earthRespirationBackSide = '''
The Earth's soil is a dynamic system, influenced by a blend of biogenic respiration and geochemical processes. To address this complexity, we're developing an advanced Earth respiration model powered by cutting-edge artificial intelligence software. This model will be trained to predict biogenic activity and fluctuations during measurement campaigns using extensive geodata, such as satellite imagery and soil gas monitoring data. Through training, the model will harness the latest AI techniques to enhance the reproducibility of soil gas analysis. By providing hands-on uncertainty estimation, it will aid in data interpretation, enabling researchers to distinguish outliers from true anomalies.
''';
